package com.eliascanalesnieto.foodhelper.presentation;

import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.time.Instant;

@Schema(name = "UserMoneyMovementResponse", description = "Money movement registered in a user's money box")
public record UserMoneyMovementResponse(
        @Schema(description = "Movement identifier", example = "1")
        Long id,
        @Schema(description = "User identifier that owns the movement", example = "1")
        Long userId,
        @Schema(description = "Signed movement amount. Positive values add money and negative values subtract money.", example = "-12.50")
        BigDecimal amount,
        @Schema(description = "Movement description", example = "Menu #7")
        String description,
        @Schema(description = "Menu related to this movement when it was generated by a menu cost", example = "7")
        Long menuId,
        @Schema(description = "UTC instant when the movement was created")
        Instant createdAt
) {
}
